{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-gradle-plugin-model",
    "version": "1.7.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.22-sources.jar",
          "url": "kotlin-gradle-plugin-model-1.7.22-sources.jar",
          "size": 7329,
          "sha512": "bf4931f33d1a6e109f6942c84e73fffeb90d6355a8260b3201ae40046949c74f1dfd0d37cfa72e96e01916c024f45e536ccd99a60b6b06ecff73fa5487e67bf9",
          "sha256": "47dd7c06f08839879b11cc54f1bb2853a9001bdb40bba4c8cff4b25136c3bf69",
          "sha1": "aeb5ff4377dd0034b5d20098263636ae00a52b4e",
          "md5": "9e325fce327ede5df7e4ce9e4cfdf3ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.22-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-1.7.22-javadoc.jar",
          "size": 316678,
          "sha512": "49061ded6aa19e16f781e29b6b5853107080f439356724a59a7f20a3d688ec10a79e1e990778973cc8f6fabc6ffec391f0043c32de29bdf3a6a39c526b7d1502",
          "sha256": "a5a9bb602cfddb737c49eaca88d149a40079f394e6425c3e358f1c286b9196b8",
          "sha1": "ff01203a5766b10797501e7e0c6dcecf9dbd66f2",
          "md5": "81d0df2e027c49747dddfec39b99b4c8"
        }
      ]
    },
    {
      "name": "runtimeElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.7.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.22.jar",
          "url": "kotlin-gradle-plugin-model-1.7.22.jar",
          "size": 12104,
          "sha512": "30e6e0c9006f633c51c65e05265699bfc0b64b0edb5e8faa6175db0e99e30a0d4803ad6478527e571227f93164f7c18611ff3695fc91817fea8ae321318423ac",
          "sha256": "e6fa7d9028eec3b6c455deeae044003aca7cc67dc5497be0b165545a625b5c0c",
          "sha1": "afe178b910a87756ef8e8cad36ba4cc3e9cb955a",
          "md5": "2163b9cbd50c314f45b58c18688e28c1"
        }
      ]
    },
    {
      "name": "apiElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.7.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.22.jar",
          "url": "kotlin-gradle-plugin-model-1.7.22.jar",
          "size": 12104,
          "sha512": "30e6e0c9006f633c51c65e05265699bfc0b64b0edb5e8faa6175db0e99e30a0d4803ad6478527e571227f93164f7c18611ff3695fc91817fea8ae321318423ac",
          "sha256": "e6fa7d9028eec3b6c455deeae044003aca7cc67dc5497be0b165545a625b5c0c",
          "sha1": "afe178b910a87756ef8e8cad36ba4cc3e9cb955a",
          "md5": "2163b9cbd50c314f45b58c18688e28c1"
        }
      ]
    },
    {
      "name": "gradle70JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.22-gradle70-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-1.7.22-gradle70-javadoc.jar",
          "size": 316678,
          "sha512": "49061ded6aa19e16f781e29b6b5853107080f439356724a59a7f20a3d688ec10a79e1e990778973cc8f6fabc6ffec391f0043c32de29bdf3a6a39c526b7d1502",
          "sha256": "a5a9bb602cfddb737c49eaca88d149a40079f394e6425c3e358f1c286b9196b8",
          "sha1": "ff01203a5766b10797501e7e0c6dcecf9dbd66f2",
          "md5": "81d0df2e027c49747dddfec39b99b4c8"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "1.7.22"
        }
      ]
    },
    {
      "name": "gradle70SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.22-gradle70-sources.jar",
          "url": "kotlin-gradle-plugin-model-1.7.22-gradle70-sources.jar",
          "size": 7329,
          "sha512": "bf4931f33d1a6e109f6942c84e73fffeb90d6355a8260b3201ae40046949c74f1dfd0d37cfa72e96e01916c024f45e536ccd99a60b6b06ecff73fa5487e67bf9",
          "sha256": "47dd7c06f08839879b11cc54f1bb2853a9001bdb40bba4c8cff4b25136c3bf69",
          "sha1": "aeb5ff4377dd0034b5d20098263636ae00a52b4e",
          "md5": "9e325fce327ede5df7e4ce9e4cfdf3ac"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "1.7.22"
        }
      ]
    },
    {
      "name": "gradle70ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.7.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle70"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.22-gradle70.jar",
          "url": "kotlin-gradle-plugin-model-1.7.22-gradle70.jar",
          "size": 12104,
          "sha512": "30e6e0c9006f633c51c65e05265699bfc0b64b0edb5e8faa6175db0e99e30a0d4803ad6478527e571227f93164f7c18611ff3695fc91817fea8ae321318423ac",
          "sha256": "e6fa7d9028eec3b6c455deeae044003aca7cc67dc5497be0b165545a625b5c0c",
          "sha1": "afe178b910a87756ef8e8cad36ba4cc3e9cb955a",
          "md5": "2163b9cbd50c314f45b58c18688e28c1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "1.7.22"
        }
      ]
    },
    {
      "name": "gradle70RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.7.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle70"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.22-gradle70.jar",
          "url": "kotlin-gradle-plugin-model-1.7.22-gradle70.jar",
          "size": 12104,
          "sha512": "30e6e0c9006f633c51c65e05265699bfc0b64b0edb5e8faa6175db0e99e30a0d4803ad6478527e571227f93164f7c18611ff3695fc91817fea8ae321318423ac",
          "sha256": "e6fa7d9028eec3b6c455deeae044003aca7cc67dc5497be0b165545a625b5c0c",
          "sha1": "afe178b910a87756ef8e8cad36ba4cc3e9cb955a",
          "md5": "2163b9cbd50c314f45b58c18688e28c1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "1.7.22"
        }
      ]
    },
    {
      "name": "gradle71JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.22-gradle71-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-1.7.22-gradle71-javadoc.jar",
          "size": 316678,
          "sha512": "49061ded6aa19e16f781e29b6b5853107080f439356724a59a7f20a3d688ec10a79e1e990778973cc8f6fabc6ffec391f0043c32de29bdf3a6a39c526b7d1502",
          "sha256": "a5a9bb602cfddb737c49eaca88d149a40079f394e6425c3e358f1c286b9196b8",
          "sha1": "ff01203a5766b10797501e7e0c6dcecf9dbd66f2",
          "md5": "81d0df2e027c49747dddfec39b99b4c8"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle71",
          "version": "1.7.22"
        }
      ]
    },
    {
      "name": "gradle71SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.22-gradle71-sources.jar",
          "url": "kotlin-gradle-plugin-model-1.7.22-gradle71-sources.jar",
          "size": 7329,
          "sha512": "bf4931f33d1a6e109f6942c84e73fffeb90d6355a8260b3201ae40046949c74f1dfd0d37cfa72e96e01916c024f45e536ccd99a60b6b06ecff73fa5487e67bf9",
          "sha256": "47dd7c06f08839879b11cc54f1bb2853a9001bdb40bba4c8cff4b25136c3bf69",
          "sha1": "aeb5ff4377dd0034b5d20098263636ae00a52b4e",
          "md5": "9e325fce327ede5df7e4ce9e4cfdf3ac"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle71",
          "version": "1.7.22"
        }
      ]
    },
    {
      "name": "gradle71ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.7.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle71"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.22-gradle71.jar",
          "url": "kotlin-gradle-plugin-model-1.7.22-gradle71.jar",
          "size": 12104,
          "sha512": "30e6e0c9006f633c51c65e05265699bfc0b64b0edb5e8faa6175db0e99e30a0d4803ad6478527e571227f93164f7c18611ff3695fc91817fea8ae321318423ac",
          "sha256": "e6fa7d9028eec3b6c455deeae044003aca7cc67dc5497be0b165545a625b5c0c",
          "sha1": "afe178b910a87756ef8e8cad36ba4cc3e9cb955a",
          "md5": "2163b9cbd50c314f45b58c18688e28c1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle71",
          "version": "1.7.22"
        }
      ]
    },
    {
      "name": "gradle71RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.7.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle71"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.22-gradle71.jar",
          "url": "kotlin-gradle-plugin-model-1.7.22-gradle71.jar",
          "size": 12104,
          "sha512": "30e6e0c9006f633c51c65e05265699bfc0b64b0edb5e8faa6175db0e99e30a0d4803ad6478527e571227f93164f7c18611ff3695fc91817fea8ae321318423ac",
          "sha256": "e6fa7d9028eec3b6c455deeae044003aca7cc67dc5497be0b165545a625b5c0c",
          "sha1": "afe178b910a87756ef8e8cad36ba4cc3e9cb955a",
          "md5": "2163b9cbd50c314f45b58c18688e28c1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle71",
          "version": "1.7.22"
        }
      ]
    }
  ]
}
