{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-settings-api",
    "version": "8.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.5.1.jar",
          "url": "gradle-settings-api-8.5.1.jar",
          "size": 9856,
          "sha512": "d2091a90401748b9be914f6448dca23099092af80584eb89767e778a7d987dc255e2dc2e0ad86ec13a7c241d99099d64a41b879f08c19fbd37a01e6e756fd6ed",
          "sha256": "82264c1cb460ffbdac88096cf71762723418b79cc331a49e561b6950df2dc1af",
          "sha1": "553c6756577609dfb65ef8882addc03c84168eb4",
          "md5": "3e0e582795d0d314b34d5c43c2a84c9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-settings-api-8.5.1.jar",
          "url": "gradle-settings-api-8.5.1.jar",
          "size": 9856,
          "sha512": "d2091a90401748b9be914f6448dca23099092af80584eb89767e778a7d987dc255e2dc2e0ad86ec13a7c241d99099d64a41b879f08c19fbd37a01e6e756fd6ed",
          "sha256": "82264c1cb460ffbdac88096cf71762723418b79cc331a49e561b6950df2dc1af",
          "sha1": "553c6756577609dfb65ef8882addc03c84168eb4",
          "md5": "3e0e582795d0d314b34d5c43c2a84c9b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.5.1-javadoc.jar",
          "url": "gradle-settings-api-8.5.1-javadoc.jar",
          "size": 261,
          "sha512": "692b7211f546d7eaff18a4972340111a674a0a17ca716971adb4547255fe25f1fbbd61bcab126f386f0df2dd13e2cce43f11290697e488721d8af2eaebc2675a",
          "sha256": "a2d290eb7cee92574814d399c82871b64f5e8e67d19a487867f1f13f1846b788",
          "sha1": "6b9c51696c76ca17d132f1fb2420454486a863a3",
          "md5": "64aba011af6f4f2ca19f9e019d06725f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.5.1-sources.jar",
          "url": "gradle-settings-api-8.5.1-sources.jar",
          "size": 9407,
          "sha512": "adada2cc53df88f1f68afdf1c8a8ac96958d6fd5477610c40e4ff5190302834a75dc5fc5b927b73477e4f7873613acfc3bb5ba18ff4ec761515d946c038d36c5",
          "sha256": "dfba04e586618cd5fee3cd5ecd91a330054af7675efadb9f9836653b9a94181a",
          "sha1": "d0b89f325fcb32a3b3a080bc37b35ab9e3c5b657",
          "md5": "37dc0e6ebc3608f45d0e299d73709245"
        }
      ]
    }
  ]
}
